import os
from django.db import models
from django.contrib.auth.models import User
from django.utils.deconstruct import deconstructible
# Create your models here.

@deconstructible
# It defines a class GenerateProfileImagePath as a deconstructible object used for generating profile image paths.
class GenerateProfileImagePath(object):
  def __init__(self):
    pass
  
  # The __call__ method of GenerateProfileImagePath constructs the path and name for the profile image file based on the instance and filename.
  def __call__(self, instance, filename):
    ext = filename.split('.')[-1]
    path = f'media/accounts/{instance.user.id}/images/'
    name = f'profile_image.{ext}'
    return os.path.join(path, name)
  
  # An instance of GenerateProfileImagePath named user_profile_image_path is created.
user_profile_image_path = GenerateProfileImagePath()
class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  # It has a FileField named image that allows uploading a file to the specified path generated by user_profile_image_path.
  image = models.FileField(upload_to=user_profile_image_path, blank=True, null=True)
  
  def __str__(self):
    return f'{self.user.username}\'s Profile'
